### ISSUE TITLE
Bitmap Compression

### ISSUE THREAD

**Issue by chemickypes** [oliveiradev/RxPhoto#4]
I'd like to help you with Bitmap Compression!
I had to work with Bitmap and often (with low memory smartphone) I got out of memory. In other situations I got a rotated or flipped bitmap.

So I'd like to add some useful methods to avoid this scenarios. 

Tell me if this is what you meant with Bitmap compression in todo list!

**Comment by oliveiradev** [comment]
Yes, its very good!

I tried it another time and had memory problems.
